apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
    spec:
      containers:
      - name: webcolor
        image: campana123/pokemon-app:v1
        ports:
        - containerPort: 80
      serviceAccountName: webcolor
