apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokemon
  namespace: argocd  
  labels:
    name: pokemon
spec:  
  project: default  
  source:
    repoURL: https://github.com/lfcampana/helm.git
    targetRevision: main  
    path: application          
    helm:      
      valueFiles:
      - values.yaml      
      values: |-
        fullnameOverride:  pipoca
        image:
          repository: campana123/pokemon-app:v2
          
        ingress:
          enabled: true          
          annotations:
            kubernetes.io/ingress.class: nginx            
          labels: {}
          hosts:
          - host: pokemonapp.192.168.49.51.nip.io        
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: pokemonapp
                  port:
                    number: 80  
  destination:    
    server: https://kubernetes.default.svc    
    namespace: pokemon